# Generated by Django 4.1.7 on 2024-07-01 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Email",
                    ),
                ),
                ("password", models.CharField(max_length=100, verbose_name="Password")),
            ],
        ),
        migrations.CreateModel(
            name="Submissions",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("code", models.CharField(max_length=2048, verbose_name="Code")),
                ("datetime", models.DateTimeField(verbose_name="Date Time")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.users"
                    ),
                ),
            ],
        ),
    ]
