# Generated by Django 4.1.7 on 2024-07-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissions",
            name="barred",
            field=models.BooleanField(default=False, verbose_name="Barred"),
            preserve_default=False,
        ),
    ]
