# Generated by Django 4.1.7 on 2024-07-03 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_submissions_barred"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "question",
                    models.CharField(max_length=1024, verbose_name="Question"),
                ),
                (
                    "solution",
                    models.CharField(max_length=1024, verbose_name="Solution"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CodeStorage",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("code", models.CharField(max_length=2048, verbose_name="Code")),
                ("question", models.IntegerField(verbose_name="Question Code")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.users"
                    ),
                ),
            ],
        ),
    ]
