# Generated by Django 4.1.7 on 2024-07-03 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_questions_codestorage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codestorage",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.questions"
            ),
        ),
    ]
