# Generated by Django 4.1.7 on 2024-07-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_codestorage_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questions",
            name="solution",
        ),
        migrations.AddField(
            model_name="questions",
            name="output",
            field=models.CharField(default="", max_length=1024, verbose_name="Output"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questions",
            name="title",
            field=models.CharField(default="", max_length=30, verbose_name="Title"),
            preserve_default=False,
        ),
    ]
