# Generated by Django 4.1.7 on 2024-07-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_questions_solution_questions_output_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="difficulty",
            field=models.CharField(
                default="M", max_length=1, verbose_name="Difficulty"
            ),
            preserve_default=False,
        ),
    ]
