# Generated by Django 4.1.7 on 2024-07-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_submissions_correct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="name",
        ),
        migrations.AddField(
            model_name="users",
            name="username",
            field=models.CharField(default="", max_length=50, verbose_name="Username"),
            preserve_default=False,
        ),
    ]
