# Generated by Django 4.1.7 on 2024-07-03 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_users_name_users_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submissions",
            name="barred",
        ),
        migrations.RemoveField(
            model_name="submissions",
            name="correct",
        ),
        migrations.AddField(
            model_name="submissions",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.questions",
            ),
        ),
    ]
