# Generated by Django 4.1.7 on 2024-07-03 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_submissions_barred_remove_submissions_correct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissions",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.questions"
            ),
        ),
    ]
