# Generated by Django 4.1.7 on 2024-07-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_submissions_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissions",
            name="correct",
            field=models.BooleanField(default=False, verbose_name="Correct"),
        ),
    ]
