# Generated by Django 4.1.7 on 2024-07-03 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_submissions_correct"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "session_code",
                    models.CharField(
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="S.Code",
                    ),
                ),
                (
                    "question",
                    models.CharField(max_length=1024, verbose_name="Question"),
                ),
                ("output", models.CharField(max_length=1024, verbose_name="Output")),
                ("start", models.DateTimeField(verbose_name="Start Time")),
                ("end", models.DateField(verbose_name="End Time")),
            ],
        ),
        migrations.RenameField(
            model_name="submissions",
            old_name="datetime",
            new_name="submit_time",
        ),
        migrations.CreateModel(
            name="CompSubmissions",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("code", models.CharField(max_length=2048, verbose_name="Code")),
                ("submit_time", models.DateTimeField(verbose_name="Date Time")),
                ("correct", models.BooleanField(default=False, verbose_name="Correct")),
                ("barred", models.BooleanField(default=False, verbose_name="Barred")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.competition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.users"
                    ),
                ),
            ],
        ),
    ]
