# Generated by Django 4.1.7 on 2024-07-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_competition_rename_datetime_submissions_submit_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissions",
            name="exec_time",
            field=models.CharField(
                default=0, max_length=10, verbose_name="Execution Time"
            ),
            preserve_default=False,
        ),
    ]
