# Generated by Django 4.1.7 on 2024-07-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_submissions_exec_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="username",
        ),
        migrations.AddField(
            model_name="users",
            name="name",
            field=models.CharField(default="hello", max_length=50, verbose_name="Name"),
            preserve_default=False,
        ),
    ]
