# Generated by Django 4.1.7 on 2024-07-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_users_username_users_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissions",
            name="exec_time",
            field=models.IntegerField(verbose_name="Execution Time"),
        ),
    ]
