# Generated by Django 4.1.7 on 2024-07-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_submissions_exec_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="end",
            field=models.DateTimeField(verbose_name="End Time"),
        ),
    ]
