# Generated by Django 4.1.7 on 2024-07-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_competition_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="compsubmissions",
            name="exec_time",
            field=models.IntegerField(default=0, verbose_name="Execution Time"),
            preserve_default=False,
        ),
    ]
