# Generated by Django 4.1.7 on 2024-07-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_compsubmissions_exec_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="grade_sec",
            field=models.CharField(default="12A", max_length=5, verbose_name="Class"),
        ),
    ]
