# Generated by Django 4.1.7 on 2024-07-12 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_users_grade_sec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="grade_sec",
            field=models.CharField(max_length=5, verbose_name="Class"),
        ),
        migrations.CreateModel(
            name="CompCodeStorage",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("code", models.CharField(max_length=2048, verbose_name="Code")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.competition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.users"
                    ),
                ),
            ],
        ),
    ]
