# Generated by Django 4.1.7 on 2024-08-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_users_grade_sec_compcodestorage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questions",
            name="output",
        ),
        migrations.AddField(
            model_name="questions",
            name="inputs",
            field=models.CharField(default="", max_length=1024, verbose_name="Inputs"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questions",
            name="outputs",
            field=models.CharField(default="", max_length=1024, verbose_name="Outputs"),
            preserve_default=False,
        ),
    ]
