# Generated by Django 4.1.7 on 2024-09-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_remove_questions_output_questions_inputs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissions",
            name="memory",
            field=models.IntegerField(default=0, verbose_name="Memory Consumed"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="submissions",
            name="submit_time",
            field=models.DateTimeField(verbose_name="Submit Time"),
        ),
    ]
