# Generated by Django 4.1.7 on 2024-09-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_submissions_memory_alter_submissions_submit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissions",
            name="exec_time",
            field=models.FloatField(verbose_name="Execution Time"),
        ),
        migrations.AlterField(
            model_name="submissions",
            name="memory",
            field=models.FloatField(verbose_name="Memory Consumed"),
        ),
    ]
