# Generated by Django 4.1.7 on 2024-09-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_submissions_exec_time_alter_submissions_memory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="output",
        ),
        migrations.AddField(
            model_name="competition",
            name="inputs",
            field=models.CharField(default="", max_length=1024, verbose_name="Inputs"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="competition",
            name="outputs",
            field=models.CharField(default="", max_length=1024, verbose_name="Outputs"),
            preserve_default=False,
        ),
    ]
