# Generated by Django 4.1.7 on 2024-09-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_remove_competition_output_competition_inputs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compsubmissions",
            name="memory",
            field=models.FloatField(default=0, verbose_name="Memory Consumed"),
            preserve_default=False,
        ),
    ]
