# Generated by Django 4.1.7 on 2024-11-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_compsubmissions_exec_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quizzes",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Quiz Title")),
                (
                    "questions",
                    models.CharField(max_length=5000, verbose_name="Questions"),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Active")),
                (
                    "single_submit",
                    models.BooleanField(default=False, verbose_name="Single Submit"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="questions",
            name="inputs",
            field=models.CharField(blank=True, max_length=1024, verbose_name="Inputs"),
        ),
        migrations.CreateModel(
            name="QuizSubmissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.CharField(max_length=10, verbose_name="Score")),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.quizzes"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.users"
                    ),
                ),
            ],
        ),
    ]
