# Generated by Django 4.1.7 on 2024-11-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_quizzes_alter_questions_inputs_quizsubmissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=1024, verbose_name="Question Text"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="quiz_images"),
                ),
                (
                    "is_multi_correct",
                    models.BooleanField(default=False, verbose_name="Multiple Correct"),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.quizzes"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Option Text")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Is Correct"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.question"
                    ),
                ),
            ],
        ),
    ]
