# Generated by Django 4.1.7 on 2024-11-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_question_option"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Quizzes",
            new_name="Quiz",
        ),
    ]
