# Generated by Django 4.1.7 on 2024-11-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_rename_quizzes_quiz"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quizzes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("questions", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("single_submit", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="quiz_images/"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="question",
            name="quiz",
        ),
        migrations.DeleteModel(
            name="Option",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.AlterField(
            model_name="quizsubmissions",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.quizzes"
            ),
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
    ]
