# Generated by Django 4.1.7 on 2024-11-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_quizzes_remove_question_quiz_delete_option_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizzes",
            name="image",
        ),
        migrations.CreateModel(
            name="QuizImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="quiz_images/")),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.quizzes",
                    ),
                ),
            ],
        ),
    ]
