# Generated by Django 4.1.7 on 2024-11-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_remove_quizzes_image_quizimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Quiz Title")),
                (
                    "questions",
                    models.CharField(max_length=5000, verbose_name="Questions"),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Active")),
                (
                    "single_submit",
                    models.BooleanField(default=False, verbose_name="Single Submit"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=1024, verbose_name="Question Text"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="quiz_images"),
                ),
                (
                    "is_multi_correct",
                    models.BooleanField(default=False, verbose_name="Multiple Correct"),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.quiz"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Option Text")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Is Correct"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.question"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="quizimage",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="core.quiz",
            ),
        ),
        migrations.AlterField(
            model_name="quizsubmissions",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.quiz"
            ),
        ),
        migrations.DeleteModel(
            name="Quizzes",
        ),
    ]
