# Generated by Django 4.1.7 on 2024-11-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_quiz_question_option_alter_quizimage_quiz_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="is_multi_correct",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="questions",
        ),
    ]
