# Generated by Django 4.1.7 on 2024-11-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_remove_question_is_multi_correct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End Time"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Start Time"
            ),
        ),
    ]
