# Generated by Django 4.1.7 on 2024-11-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_quiz_end_time_quiz_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="option_images"),
        ),
    ]
