# Generated by Django 4.1.7 on 2024-11-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_option_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="grade",
            field=models.IntegerField(default=0, verbose_name="Grade"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="section",
            field=models.CharField(default="A", max_length=1, verbose_name="Section"),
            preserve_default=False,
        ),
    ]
