# Generated by Django 4.1.7 on 2024-11-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_quiz_grade_quiz_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsubmissions",
            name="submit_time",
            field=models.DateTimeField(null=True, verbose_name="Submit Time"),
        ),
        migrations.DeleteModel(
            name="QuizImage",
        ),
    ]
