# Generated by Django 4.1.7 on 2024-11-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_quizsubmissions_submit_time_delete_quizimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizsubmissions",
            name="submit_time",
            field=models.DateTimeField(verbose_name="Submit Time"),
        ),
    ]
