# Generated by Django 4.1.7 on 2024-11-12 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_remove_quizsubmissions_quiz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizsubmissions",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.question"
            ),
        ),
    ]
