# Generated by Django 4.1.7 on 2024-11-12 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_quizsubmissions_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsubmissions",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.option",
            ),
        ),
    ]
