# Generated by Django 4.1.7 on 2024-11-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_quizsubmissions_selected_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
