# Generated by Django 4.1.7 on 2024-11-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_alter_option_id_alter_question_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="active",
        ),
    ]
