# Generated by Django 4.1.7 on 2024-11-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_remove_quiz_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizsubmissions",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
