# Generated by Django 4.1.7 on 2024-11-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_alter_quizsubmissions_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="points",
            field=models.IntegerField(default=0, verbose_name="Points"),
        ),
        migrations.AddField(
            model_name="questions",
            name="points",
            field=models.IntegerField(default=0, verbose_name="Points"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="points",
            field=models.IntegerField(default=0, verbose_name="Points"),
        ),
        migrations.AddField(
            model_name="users",
            name="points",
            field=models.IntegerField(default=0, verbose_name="Points"),
        ),
    ]
