# Generated by Django 4.1.7 on 2025-01-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_competition_points_questions_points_quiz_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="competition_points",
            field=models.IntegerField(default=0, verbose_name="Competition Points"),
        ),
        migrations.AddField(
            model_name="users",
            name="question_points",
            field=models.IntegerField(default=0, verbose_name="Question Points"),
        ),
        migrations.AddField(
            model_name="users",
            name="quiz_points",
            field=models.IntegerField(default=0, verbose_name="Quiz Points"),
        ),
    ]
