# Generated by Django 4.1.7 on 2025-01-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_remove_users_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="Updates",
            fields=[
                (
                    "id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "description",
                    models.CharField(max_length=1024, verbose_name="Description"),
                ),
                ("date", models.DateTimeField(verbose_name="Date")),
            ],
        ),
    ]
