# Generated by Django 4.1.7 on 2025-01-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alter_updates_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="updates",
            name="date",
            field=models.DateTimeField(verbose_name="Date"),
        ),
    ]
